#!/bin/bash

# User 1
curl -X POST -H "Content-Type: application/json" -d '{"name": "Thabo Mbeki", "email": "thabo.mbeki1@example.com", "govtId": "ZWE123456789", "phone_number": "+263712345671", "house_number": "1", "town": "Harare", "city": "Harare", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 2
curl -X POST -H "Content-Type: application/json" -d '{"name": "Ngozi Okonjo-Iweala", "email": "ngozi.okonjo-iweala2@example.com", "govtId": "ZWE234567890", "phone_number": "+263712345672", "house_number": "2", "town": "Bulawayo", "city": "Bulawayo", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 3
curl -X POST -H "Content-Type: application/json" -d '{"name": "Amina Mohammed", "email": "amina.mohammed3@example.com", "govtId": "ZWE345678901", "phone_number": "+263712345673", "house_number": "3", "town": "Mutare", "city": "Manicaland", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 4
curl -X POST -H "Content-Type: application/json" -d '{"name": "Patrice Lumumba", "email": "patrice.lumumba4@example.com", "govtId": "ZWE456789012", "phone_number": "+263712345674", "house_number": "4", "town": "Gweru", "city": "Midlands", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 5
curl -X POST -H "Content-Type: application/json" -d '{"name": "Wangari Maathai", "email": "wangari.maathai5@example.com", "govtId": "ZWE567890123", "phone_number": "+263712345675", "house_number": "5", "town": "Masvingo", "city": "Masvingo", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 15
curl -X POST -H "Content-Type: application/json" -d '{"name": "Kwame Nkrumah", "email": "kwame.nkrumah15@example.com", "govtId": "ZWE567890123", "phone_number": "+263712345685", "house_number": "15", "town": "Mutare", "city": "Manicaland", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 16
curl -X POST -H "Content-Type: application/json" -d '{"name": "Thabo Mbeki", "email": "thabo.mbeki16@example.com", "govtId": "ZWE678901234", "phone_number": "+263712345686", "house_number": "16", "town": "Masvingo", "city": "Masvingo", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 17
curl -X POST -H "Content-Type: application/json" -d '{"name": "Nelson Mandela", "email": "nelson.mandela17@example.com", "govtId": "ZWE789012345", "phone_number": "+263712345687", "house_number": "17", "town": "Gweru", "city": "Midlands", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 18
curl -X POST -H "Content-Type: application/json" -d '{"name": "Chinua Achebe", "email": "chinua.achebe18@example.com", "govtId": "ZWE890123456", "phone_number": "+263712345688", "house_number": "18", "town": "Shurugwi", "city": "Midlands", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 19
curl -X POST -H "Content-Type: application/json" -d '{"name": "Ellen Johnson Sirleaf", "email": "ellen.johnson-sirleaf19@example.com", "govtId": "ZWE901234567", "phone_number": "+263712345689", "house_number": "19", "town": "Beitbridge", "city": "Matabeleland South", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 20
curl -X POST -H "Content-Type: application/json" -d '{"name": "Winnie Madikizela-Mandela", "email": "winnie.madikizela-mandela20@example.com", "govtId": "ZWE012345678", "phone_number": "+263712345690", "house_number": "20", "town": "Bulawayo", "city": "Bulawayo", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 21
curl -X POST -H "Content-Type: application/json" -d '{"name": "Nelson Mandela", "email": "nelson.mandela21@example.com", "govtId": "ZWE123456789", "phone_number": "+263712345691", "house_number": "21", "town": "Kadoma", "city": "Mashonaland West", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 22
curl -X POST -H "Content-Type: application/json" -d '{"name": "Julius Malema", "email": "julius.malema22@example.com", "govtId": "ZWE234567890", "phone_number": "+263712345692", "house_number": "22", "town": "Chinhoyi", "city": "Mashonaland West", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 23
curl -X POST -H "Content-Type: application/json" -d '{"name": "Wangari Maathai", "email": "wangari.maathai23@example.com", "govtId": "ZWE345678901", "phone_number": "+263712345693", "house_number": "23", "town": "Marondera", "city": "Mashonaland East", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 24
curl -X POST -H "Content-Type: application/json" -d '{"name": "Kwame Nkrumah", "email": "kwame.nkrumah24@example.com", "govtId": "ZWE456789012", "phone_number": "+263712345694", "house_number": "24", "town": "Mutare", "city": "Manicaland", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

# User 25
curl -X POST -H "Content-Type: application/json" -d '{"name": "Thabo Mbeki", "email": "thabo.mbeki25@example.com", "govtId": "ZWE567890123", "phone_number": "+263712345695", "house_number": "25", "town": "Masvingo", "city": "Masvingo", "country": "Zimbabwe", "status": "Active"}' http://localhost:5000/api/create_user

