import { Inter } from "next/font/google";
import { AppSidebar } from "@/components/app-sidebar";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider defaultOpen>
          <div className="flex">
            <AppSidebar />
            <SidebarInset className="flex-1">{children}</SidebarInset>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import "./globals.css";
// import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
// import { AppSidebar } from "@/components/app-sidebar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <SidebarProvider defaultOpen>
//           <SidebarInset className="flex-1">
//             <AppSidebar />
//             {children}
//           </SidebarInset>
//         </SidebarProvider>
//       </body>
//     </html>
//   );
// }
